import {startRecording,ReplyAudio} from './voice.js';
import './style.css';
import Guacamole from './guacamole.js';
import {Terminal} from '@xterm/xterm';
import {FitAddon} from '@xterm/addon-fit';
import {EditorView,basicSetup} from 'codemirror';
import {languages} from '@codemirror/language-data';
import {oneDark} from '@codemirror/theme-one-dark';
import {startRegistration,startAuthentication} from '@simplewebauthn/browser';

const $=s=>document.querySelector(s), main=$('#main');
let beforeNavigate=()=>true;
let csrf='', current='home', cleanup=()=>{}, authenticated=false, networkTimer, renderId=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const pretty=o=>JSON.stringify(o,null,2);
const bytes=n=>n==null?'Unavailable':n>1073741824?(n/1073741824).toFixed(1)+' GB':(n/1048576).toFixed(0)+' MB';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function notice(text=''){ $('#notice').textContent=text;$('#notice').classList.toggle('visible',!!text); }
function status(text,ok=false){$('#connection').textContent=text;$('#connection').classList.toggle('online',ok);}
function bind(id,fn){$(id)?.addEventListener('click',()=>{try{Promise.resolve(fn()).catch(e=>notice(e.message));}catch(e){notice(e.message);}});}
async function api(path,data){
 const res=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:data===undefined?{'X-Carlos-API-Version':'1'}:{'X-Carlos-API-Version':'1','Content-Type':'application/json','X-HoloHand-CSRF':csrf},body:data===undefined?undefined:JSON.stringify(data)});
 const obj=await res.json();if(!res.ok){if(res.status===401){authenticated=false;status('UNLOCK REQUIRED');}throw new Error(obj.error||'Request failed');}return obj;
}
function wsurl(path){return `${location.protocol==='https:'?'wss':'ws'}://${location.host}${path}`;}
async function dangerous(action,target,text){
 if(!window.confirm(text))return null;
 return (await api('confirm',{action,target})).confirmation;
}
async function unlock(){
 const options=await api('login/options',{});const credential=await startAuthentication({optionsJSON:options});
 const s=await api('login/finish',credential);csrf=s.csrf;authenticated=true;status("● CONNECTED",true);notice();await navigate(current);
}
function login(){
 cleanup();main.innerHTML=`<section class="pair"><img src="/icon-180.png" alt="Carlos"><div class="eyebrow">YOUR COMPUTER. WITH YOU.</div><h1>Carlos Mobile</h1><p class="muted">Secure access to your desktop, projects and tools.</p><button id="unlock" class="primary wide">Unlock with passkey</button><details><summary>Pair this iPhone</summary><p>Enter the code shown on your computer. Pairing creates a passkey protected by your iPhone.</p><input id="device-name" value="My iPhone" aria-label="Device name"><input id="pair-code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" placeholder="Six-digit code" aria-label="Pairing code"><button id="pair" class="wide primary">Pair with computer</button></details><p class="details">Connect Tailscale before opening Carlos Mobile. Add this page to your Home Screen in Safari for the full app experience.</p></section>`;
 bind('#unlock',unlock);bind('#pair',async()=>{const o=await api('pair/options',{code:$('#pair-code').value,name:$('#device-name').value});const c=await startRegistration({optionsJSON:o});const s=await api('pair/finish',c);csrf=s.csrf;authenticated=true;status("● CONNECTED",true);notice();await navigate('home');});
}
async function navigate(page){
 if(!beforeNavigate())return;beforeNavigate=()=>true;
 if(!authenticated){current=page;login();return;}
 cleanup();cleanup=()=>{};current=page;localStorage.setItem('hh-page',page);renderId++;notice();
 document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
 main.innerHTML='<p class="muted spinner">Connecting…</p>';
 try{await ({home,desktop:desktopPage,terminal:terminalPage,codex:codexPage,files:filesPage,system:systemPage,ev:evPage,settings,more,chat:chatPage,diagnostics}[page]||home)();}
 catch(e){main.innerHTML=`<h1>${esc(page)}</h1><p class="message">${esc(e.message)}</p><button id="retry">${authenticated?'Try again':'Unlock with passkey'}</button>`;bind('#retry',()=>authenticated?navigate(page):unlock());}
}
async function home(){
 const d=await api('system'); const temp=d.temperatures.find(t=>/package/i.test(t.label))||d.temperatures[0];
 main.innerHTML=`<div class="eyebrow">PERSONAL CONNECTION</div><div class="topbar"><h1>${esc(d.host.toUpperCase())}</h1><span class="online">● CONNECTED</span></div><p class="muted">Your workspace is right here.</p><div class="grid"><div class="card metric"><small>CPU</small><strong>${d.cpu.toFixed(0)}%</strong></div><div class="card metric"><small>MEMORY</small><strong>${bytes(d.ram.used)}</strong><small>of ${bytes(d.ram.total)}</small></div><div class="card metric"><small>TEMPERATURE</small><strong>${temp?temp.celsius.toFixed(0)+'°':'—'}</strong></div><div class="card metric"><small>UPTIME</small><strong>${Math.floor(d.uptime/3600)}h ${Math.floor(d.uptime/60)%60}m</strong></div></div><button class="hero" id="desktop-hero"><div class="eyebrow">LIVE FROM YOUR COMPUTER</div><strong>Desktop ↗</strong><span>Open your real Plasma workspace</span></button><div class="grid">${[['codex','Codex','Your coding agent'],['terminal','Terminal','A real Linux shell'],['files','Files','Browse & edit'],['ev','Carlos','Your assistant']].map(([p,t,s])=>`<button class="tile" data-go="${p}">${t}<small style="display:block;margin-top:8px">${s}</small></button>`).join('')}</div><div class="row"><button id="quick-firefox">Firefox</button><button id="quick-lock">Lock PC</button><button data-go="system">System</button><button data-go="chat">Chat</button></div>`;
 bind('#desktop-hero',()=>navigate('desktop'));bind('#quick-firefox',()=>api('action',{action:'firefox'}));bind('#quick-lock',async()=>{await api('action',{action:'lock'});notice('Computer locked.');});
 bindNavigation();
}
function bindNavigation(){main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));}
async function more(){main.innerHTML='<h1>Your tools</h1><div class="grid">'+[['files','Files & editor'],['system','System'],['ev','Carlos'],['chat','Carlos chat'],['settings','Paired devices'],['diagnostics','Connection']].map(([p,t])=>`<button class="tile" data-go="${p}">${t}</button>`).join('')+'</div>';bindNavigation();}

const keysyms={CTRL:0xffe3,ALT:0xffe9,SUPER:0xffeb,SHIFT:0xffe1,TAB:0xff09,ESC:0xff1b,ENTER:0xff0d,BACKSPACE:0xff08,DELETE:0xffff,'↑':0xff52,'↓':0xff54,'←':0xff51,'→':0xff53};
async function desktopPage(){
 await api('desktop/authorize',{});
 const displays=await api('monitors');let quality=localStorage.getItem('hh-quality')||'auto';let monitor=localStorage.getItem('hh-monitor')||'0';let mode=localStorage.getItem('hh-mode')||'direct';
 main.innerHTML=`<div class="topbar"><h2>Desktop</h2><button id="stop-desktop">Disconnect</button></div><div class="desktop-controls"><select id="monitor" aria-label="Monitor">${displays.map((d,i)=>`<option value="${i}">${esc(d.name)}${d.mode?' · '+d.mode.size.width+'×'+d.mode.size.height:''}</option>`).join('')}<option value="-1" disabled>Combined view unavailable</option></select><select id="quality" aria-label="Quality">${[['auto','AUTO'],['saver','DATA SAVER'],['balanced','BALANCED'],['ultra','ULTRA']].map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div><div class="row"><button id="mode">${mode==='direct'?'DIRECT':'TRACKPAD'}</button><button id="zoom">Zoom 1×</button><button id="show-keyboard">⌨ Keyboard</button><button id="toolbar">Tools</button></div><div id="desktop-wrap" class="desktop-wrap"><div id="desktop-surface" class="desktop-surface"></div></div><div id="trackpad" class="trackpad ${mode==='direct'?'hidden':''}">Trackpad · two fingers to scroll</div><div id="desktop-tools"><div id="desktop-keys" class="keyboard-strip"></div><div class="row"><button id="right-click">Right click</button><button id="drag">Hold to drag</button><button id="paste-pc">Paste to PC</button><button id="copy-phone">Copy to phone</button><button id="screenshot">Screenshot</button></div></div><input id="phone-keyboard" class="phone-keyboard" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" aria-label="Desktop keyboard"><p id="desktop-state" class="details">Connecting to KDE…</p>`;
 $('#monitor').value=monitor;$('#quality').value=quality;
 let client,tunnel,closed=false,retry=0,retryTimer,zoom=1,baseScale=1,pointer={x:0,y:0,left:false,middle:false,right:false,up:false,down:false},clipboard='',mods=new Set(),latency=0;
 const surface=$('#desktop-surface'),wrap=$('#desktop-wrap'),state=$('#desktop-state');
 function fit(){if(!client)return;const d=client.getDisplay();if(!d.getWidth())return;baseScale=wrap.clientWidth/d.getWidth();d.scale(baseScale*zoom);surface.style.width=d.getWidth()*baseScale*zoom+'px';surface.style.height=d.getHeight()*baseScale*zoom+'px';}
 function mouse(){client?.sendMouseState(new Guacamole.Mouse.State(pointer.x,pointer.y,pointer.left,pointer.middle,pointer.right,pointer.up,pointer.down));}
 function key(code){client?.sendKeyEvent(1,code);client?.sendKeyEvent(0,code);for(const m of mods)client?.sendKeyEvent(0,keysyms[m]);mods.clear();$('#desktop-keys').querySelectorAll('.active').forEach(e=>e.classList.remove('active'));}
 function text(value){for(const c of value){const cp=c.codePointAt(0);key(cp<256?cp:0x01000000|cp);}}
 async function connect(){
  if(closed)return;
  try{await api('desktop/authorize',{});}catch(e){if(closed)return;state.textContent=e.message;const b=document.createElement('button');b.textContent=authenticated?'Retry desktop':'Unlock with passkey';b.onclick=()=>navigate('desktop');state.append(b);return;}
  if(closed)return;surface.innerHTML='';tunnel=new Guacamole.WebSocketTunnel(wsurl('/ws/desktop'));client=new Guacamole.Client(tunnel);surface.appendChild(client.getDisplay().getElement());
  client.getDisplay().statisticWindow=1000;
  client.getDisplay().onstatistics=s=>{if(closed)return;const measurement={clientFps:s.clientFps,desktopFps:s.desktopFps,processingLag:s.processingLag,dropRate:s.dropRate,measuredAt:Date.now()};sessionStorage.setItem('hh-stream-measurement',JSON.stringify(measurement));state.textContent=`Live desktop · ${s.clientFps==null?'—':s.clientFps.toFixed(0)} frames/s · ${Math.round(s.processingLag)} ms render queue`;};
  client.getDisplay().onresize=()=>{fit();if(client.getDisplay().getWidth()>0){retry=0;state.textContent='Live desktop';}};
  client.onstatechange=s=>{state.textContent=['Idle','Connecting…','Waiting for desktop…','Live desktop','Disconnecting…','Disconnected'][s]||'Connecting…';if(s===3){state.textContent='Waiting for desktop frames…';fit();}if(s===5&&!closed){retryTimer=setTimeout(connect,Math.min(15000,1000*2**retry++)+Math.random()*300);}};
  client.onerror=e=>{state.textContent=`Desktop: ${e.message}. Reconnecting…`;};
  client.onclipboard=(stream,mimetype)=>{if(mimetype!=='text/plain')return;const reader=new Guacamole.StringReader(stream);let value='';reader.ontext=t=>{if(value.length<65536)value+=t;};reader.onend=()=>clipboard=value;};
  tunnel.onstatechange=s=>{if(s===2&&!closed)state.textContent='Network interrupted. Reconnecting…';};
  client.connect(`monitor=${encodeURIComponent(monitor)}&quality=${encodeURIComponent(quality)}`);
 }
 connect();const resize=new ResizeObserver(fit);resize.observe(wrap);
 $('#monitor').onchange=()=>{localStorage.setItem('hh-monitor',$('#monitor').value);navigate('desktop');};
 $('#quality').onchange=()=>{localStorage.setItem('hh-quality',$('#quality').value);navigate('desktop');};
 bind('#stop-desktop',()=>navigate('home'));bind('#mode',()=>{mode=mode==='direct'?'trackpad':'direct';localStorage.setItem('hh-mode',mode);$('#mode').textContent=mode.toUpperCase();$('#trackpad').classList.toggle('hidden',mode==='direct');});
 bind('#zoom',()=>{zoom=zoom===1?2:zoom===2?3:1;$('#zoom').textContent=`Zoom ${zoom}×`;fit();});
 bind('#toolbar',()=>$('#desktop-tools').classList.toggle('hidden'));
 const strip=$('#desktop-keys');for(const label of ['CTRL','ALT','SUPER','SHIFT','TAB','ESC','↑','↓','←','→','DELETE','/','~','-','_','|','{','}','[',']']){const b=document.createElement('button');b.textContent=label;strip.append(b);b.onclick=()=>{if(['CTRL','ALT','SUPER','SHIFT'].includes(label)){mods.has(label)?mods.delete(label):mods.add(label);client.sendKeyEvent(mods.has(label)?1:0,keysyms[label]);b.classList.toggle('active',mods.has(label));}else key(keysyms[label]||label.charCodeAt(0));};}
 const keyboard=$('#phone-keyboard');const resetKeyboard=()=>{keyboard.value='\u200b';keyboard.setSelectionRange(1,1);};
 keyboard.placeholder='Tap here to type on your computer';
 bind('#show-keyboard',()=>{keyboard.focus();keyboard.scrollIntoView({block:'center'});});
 keyboard.addEventListener('focus',resetKeyboard);
 keyboard.addEventListener('blur',()=>{keyboard.value='';});
 keyboard.addEventListener('input',e=>{if(e.isComposing)return;if(e.inputType==='deleteContentBackward')key(keysyms.BACKSPACE);else if(e.inputType==='insertLineBreak')key(keysyms.ENTER);else if(e.data)text(e.data);else{const value=keyboard.value.replace(/\u200b/g,'');if(value)text(value);}resetKeyboard();});
 keyboard.addEventListener('keydown',e=>{const map={Enter:'ENTER',Backspace:'BACKSPACE',Tab:'TAB',Escape:'ESC',Delete:'DELETE',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→'};if(map[e.key]){e.preventDefault();key(keysyms[map[e.key]]);}});
 let longTimer,gesture=null,lastTap=0;const touchTargets=[wrap,$('#trackpad')];
 for(const target of touchTargets){
  const direct=target===wrap;
  target.addEventListener('touchstart',e=>{e.preventDefault();if(direct&&mode!=='direct')return;clearTimeout(longTimer);const t=e.touches[0];const r=surface.getBoundingClientRect();gesture={x:t.clientX,y:t.clientY,startX:t.clientX,startY:t.clientY,time:Date.now(),count:e.touches.length,moved:false,right:false};if(direct){pointer.x=(t.clientX-r.left)/(baseScale*zoom);pointer.y=(t.clientY-r.top)/(baseScale*zoom);mouse();}if(e.touches.length===1)longTimer=setTimeout(()=>{if(gesture&&!gesture.moved){pointer.right=true;mouse();pointer.right=false;mouse();gesture.right=true;}},550);if(e.touches.length===2){gesture.distance=Math.hypot(e.touches[1].clientX-t.clientX,e.touches[1].clientY-t.clientY);gesture.zoom=zoom;pointer.left=false;mouse();}},{passive:false});
  target.addEventListener('touchmove',e=>{e.preventDefault();if(!gesture)return;const t=e.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(Math.hypot(t.clientX-gesture.startX,t.clientY-gesture.startY)>6){gesture.moved=true;clearTimeout(longTimer);}if(e.touches.length===2){const distance=Math.hypot(e.touches[1].clientX-t.clientX,e.touches[1].clientY-t.clientY);if(direct&&Math.abs(distance-(gesture.distance||distance))>15){zoom=Math.max(1,Math.min(4,(gesture.zoom||1)*distance/(gesture.distance||distance)));fit();}else if(Math.abs(dy)>3){pointer[dy>0?'up':'down']=true;mouse();pointer.up=pointer.down=false;mouse();}}else{if(direct){const r=surface.getBoundingClientRect();pointer.x=(t.clientX-r.left)/(baseScale*zoom);pointer.y=(t.clientY-r.top)/(baseScale*zoom);if(gesture.moved&&!gesture.right)pointer.left=true;}else{pointer.x=Math.max(0,Math.min(client.getDisplay().getWidth()-1,pointer.x+dx/baseScale));pointer.y=Math.max(0,Math.min(client.getDisplay().getHeight()-1,pointer.y+dy/baseScale));}mouse();}gesture.x=t.clientX;gesture.y=t.clientY;},{passive:false});
  target.addEventListener('touchend',e=>{e.preventDefault();clearTimeout(longTimer);if(!gesture)return;if(!gesture.moved&&!gesture.right&&gesture.count===1){pointer.left=true;mouse();pointer.left=false;mouse();if(direct&&Date.now()-lastTap<320){zoom=zoom===1?2:1;fit();}lastTap=Date.now();}pointer.left=false;mouse();gesture=null;},{passive:false});
  target.addEventListener('touchcancel',()=>{clearTimeout(longTimer);pointer.left=pointer.right=false;mouse();gesture=null;});
 }
 const nativeMouse=new Guacamole.Mouse(surface);nativeMouse.onmousedown=nativeMouse.onmouseup=nativeMouse.onmousemove=s=>{if(mode!=='direct')return;pointer={...s,x:s.x/(baseScale*zoom),y:s.y/(baseScale*zoom)};mouse();};
 bind('#right-click',()=>{pointer.right=true;mouse();pointer.right=false;mouse();});
 $('#drag').onpointerdown=e=>{e.preventDefault();pointer.left=true;mouse();$('#drag').setPointerCapture(e.pointerId);};$('#drag').onpointerup=$('#drag').onpointercancel=()=>{pointer.left=false;mouse();};
 bind('#paste-pc',async()=>{const value=await navigator.clipboard.readText();const stream=client.createClipboardStream('text/plain');const writer=new Guacamole.StringWriter(stream);writer.sendText(value.slice(0,65536));writer.sendEnd();notice('Text clipboard sent to PC.');});
 bind('#copy-phone',async()=>{await navigator.clipboard.writeText(clipboard);notice('PC text clipboard copied.');});
 bind('#screenshot',()=>{const a=document.createElement('a');a.download='HoloHand-desktop.png';a.href=client.getDisplay().flatten().toDataURL('image/png');a.click();});
 cleanup=()=>{closed=true;clearTimeout(retryTimer);clearTimeout(longTimer);resize.disconnect();mods.forEach(m=>client.sendKeyEvent(0,keysyms[m]));pointer.left=pointer.right=false;mouse();client?.disconnect();};
}

async function terminalPage(){
 let sessions=await api('terminals');main.innerHTML=`<h1>Terminal</h1><div class="row"><select id="term-select" aria-label="Terminal session">${sessions.map((s,i)=>`<option value="${s.id}">Shell ${i+1}${s.running?'':' (closed)'}</option>`).join('')}</select><button id="term-new">New</button><button id="term-close">Close</button><button id="term-keyboard">⌨</button></div><div id="term" class="terminal"></div><div id="term-keys" class="keyboard-strip"></div><p id="term-status" class="details">Opening shell…</p>`;
 let id=sessions.find(s=>s.running)?.id;if(!id)id=(await api('terminals',{cwd:'.'})).id;
 const term=new Terminal({fontSize:13,fontFamily:'monospace',cursorBlink:true,theme:{background:'#080d16',foreground:'#e2f0f9'},scrollback:3000});const fit=new FitAddon();term.loadAddon(fit);term.open($('#term'));fit.fit();
 let socket,closed=false,retries=0,timer,seq=0;const encoder=new TextEncoder();
 const encode=s=>btoa(String.fromCharCode(...encoder.encode(s)));
 const send=s=>{if(socket?.readyState===1)socket.send(JSON.stringify({type:'input',data:encode(s)}));};
 function connect(){socket=new WebSocket(wsurl(`/ws/terminal/${id}?since=${seq}`));socket.onopen=()=>{retries=0;$('#term-status').textContent='Connected · real host shell';socket.send(JSON.stringify({type:'resize',cols:term.cols,rows:term.rows}));};socket.onmessage=e=>{const d=JSON.parse(e.data);seq=d.seq;term.write(Uint8Array.from(atob(d.data),c=>c.charCodeAt(0)));};socket.onclose=()=>{if(!closed){$('#term-status').textContent='Disconnected · reconnecting';timer=setTimeout(connect,Math.min(15000,1000*2**retries++));}};}
 connect();term.onData(send);term.onResize(s=>{if(socket?.readyState===1)socket.send(JSON.stringify({type:'resize',...s}));});const observer=new ResizeObserver(()=>fit.fit());observer.observe($('#term'));
 for(const [label,value] of [['CTRL+C','\x03'],['CTRL+D','\x04'],['CTRL+Z','\x1a'],['TAB','\t'],['ESC','\x1b'],['↑','\x1b[A'],['↓','\x1b[B'],['←','\x1b[D'],['→','\x1b[C'],['ENTER','\r'],['/','/'],['~','~'],['|','|']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>send(value);$('#term-keys').append(b);}
 bind('#term-keyboard',()=>term.focus());bind('#term-new',async()=>{await api('terminals',{cwd:'.'});await navigate('terminal');});
 bind('#term-close',async()=>{await api('terminals/close',{id});navigate('terminal');});
 $('#term-select').onchange=()=>{closed=true;socket.close();id=$('#term-select').value;seq=0;term.reset();closed=false;connect();};
 cleanup=()=>{closed=true;clearTimeout(timer);socket?.close();observer.disconnect();term.dispose();};
}

function codexRequest(event){
 const p=event.params,card=document.createElement('div');card.className='card';
 card.innerHTML='<h2>Codex needs your input</h2>';
 const submit=async(data)=>{try{await api('codex',{action:'respond',requestId:event.requestId,...data});card.remove();}catch(e){notice(e.message);}};
 if(event.method.endsWith('/requestUserInput')){
  const inputs=new Map();
  for(const q of p.questions||[]){
   const label=document.createElement('label');label.textContent=q.question;card.append(label);
   const input=document.createElement('input');input.className='wide';input.type=q.isSecret?'password':'text';input.autocomplete='off';input.setAttribute('aria-label',q.question);card.append(input);inputs.set(q.id,input);
   const options=document.createElement('div');options.className='row';
   for(const option of q.options||[]){const b=document.createElement('button');b.textContent=option.label;b.title=option.description;b.onclick=()=>{input.value=option.label;};options.append(b);}card.append(options);
  }
  const b=document.createElement('button');b.textContent='Send answers';b.onclick=()=>submit({answers:Object.fromEntries([...inputs].map(([id,input])=>[id,{answers:[input.value]}]))});card.append(b);
 }else{
  const detail=document.createElement('pre');detail.className='output';detail.textContent=p.command||p.reason||pretty(p);card.append(detail);
  if(p.reason&&p.command){const reason=document.createElement('p');reason.textContent=p.reason;card.append(reason);}
  for(const decision of ['accept','decline']){const b=document.createElement('button');b.textContent=decision==='accept'?'Approve once':'Decline';b.onclick=()=>submit({decision});card.append(b);}
 }
 $('#codex-approvals').append(card);
}

async function codexPage(){
 const sessions=await api('codex');let thread=localStorage.getItem('hh-thread');if(!sessions.some(t=>t.id===thread))thread=sessions[0]?.id;
 main.innerHTML=`<div class="topbar"><h1>Codex</h1><button data-go="desktop">View Desktop</button></div><div class="row"><input id="project" value="${esc(sessions.find(t=>t.id===thread)?.cwd||'.')}" aria-label="Project directory"><button id="codex-new">New session</button></div><select id="codex-session" class="wide" aria-label="Codex session">${sessions.map(t=>`<option value="${t.id}">${esc(t.cwd)} · ${esc(t.status)}</option>`).join('')}</select><p id="codex-state" class="eyebrow">${thread?'READY':'START A SESSION'}</p><div id="codex-messages"></div><div id="codex-approvals"></div><div class="chat-compose"><textarea id="codex-input" rows="3" placeholder="Message Codex…"></textarea><div class="row"><button id="codex-send" class="primary">Send</button><button id="codex-cancel">Cancel</button><button id="codex-git">Git changes</button></div></div><pre id="git-output" class="output hidden"></pre>`;
 bindNavigation();if(thread)$('#codex-session').value=thread;
 const messages=$('#codex-messages');let seq=0,closed=false,timer;const items=new Map();
 const item=(id,text)=>{let node=items.get(id);if(!node){node=document.createElement('div');node.className='message';items.set(id,node);messages.append(node);}node.textContent=text;};
 if(thread){try{const r=await api('codex',{action:'read',thread});for(const turn of r.thread.turns||[])for(const i of turn.items||[]){if(i.type==='agentMessage')item(i.id,i.text);if(i.type==='userMessage')item(i.id,(i.content||[]).map(x=>x.text||'').join('\n'));}}catch(e){notice(e.message);}}
 async function poll(){if(closed)return;try{const list=await api('codex/events?since='+seq);for(const e of list){seq=Math.max(seq,e.seq);if(e.threadId!==thread)continue;const p=e.params;if(e.method==='item/agentMessage/delta'){const id=p.itemId;item(id,(items.get(id)?.textContent||'')+p.delta);}if(e.method==='item/completed'&&p.item?.type==='agentMessage')item(p.item.id,p.item.text);if(e.method==='turn/started')$('#codex-state').textContent='WORKING';if(e.method==='turn/completed')$('#codex-state').textContent=p.turn.status.toUpperCase();if(e.requestId!==null&&e.requestId!==undefined){$('#codex-state').textContent='WAITING FOR YOU';codexRequest(e);}}}catch(e){notice(e.message);}finally{if(!closed)timer=setTimeout(poll,1500);}}
 poll();bind('#codex-new',async()=>{const r=await api('codex',{action:'start',cwd:$('#project').value});localStorage.setItem('hh-thread',r.id);navigate('codex');});
 bind('#codex-send',async()=>{const text=$('#codex-input').value.trim();if(!text)return;if(!thread){const r=await api('codex',{action:'start',cwd:$('#project').value});thread=r.id;localStorage.setItem('hh-thread',thread);}await api('codex',{action:'prompt',thread,text});item('user-'+Date.now(),text);$('#codex-input').value='';$('#codex-state').textContent='WORKING';});
 bind('#codex-cancel',()=>api('codex',{action:'cancel',thread}));bind('#codex-git',async()=>{const d=await api('git?cwd='+encodeURIComponent($('#project').value));$('#git-output').textContent=d.status.stdout+'\n'+d.diff.stdout;$('#git-output').classList.remove('hidden');});
 $('#codex-session').onchange=()=>{localStorage.setItem('hh-thread',$('#codex-session').value);navigate('codex');};
 cleanup=()=>{closed=true;clearTimeout(timer);};
}

async function filesPage(){
 let path=localStorage.getItem('hh-path')||'.',editor=null,dirty=false,revision=null,file=null;
 beforeNavigate=()=>!dirty||confirm('Discard unsaved edits?');
 main.innerHTML=`<h1>Files</h1><div class="row"><button id="files-up">↑</button><input id="file-path" aria-label="Folder path" value="${esc(path)}"><button id="files-go">Go</button></div><div class="row"><input id="file-search" placeholder="Search this folder" aria-label="Search files"><button id="file-new">New file</button><button id="folder-new">Folder +</button><button id="upload">Upload</button><input id="upload-input" type="file" class="hidden"></div><div id="file-list" class="list"></div><section id="file-editor" class="hidden"><div class="row"><span id="editor-name" class="path"></span><span id="dirty"></span><button id="file-save" class="primary">Save</button><button id="file-download">Download</button><button id="file-rename">Move / rename</button><button id="file-copy">Copy</button><button id="file-delete" class="danger">Delete</button></div><div id="editor" class="editor"></div><img id="image-preview" class="preview-image hidden" alt="File preview"></section>`;
 const join=name=>(path==='.'?'':path.replace(/\/$/,'')+'/')+name;
 async function browse(){if(dirty&&!confirm('Discard unsaved edits?'))return;editor?.destroy();editor=null;dirty=false;$('#file-editor').classList.add('hidden');const d=await api('files?path='+encodeURIComponent(path)+'&search='+encodeURIComponent($('#file-search').value));localStorage.setItem('hh-path',path);$('#file-path').value=path;$('#file-list').innerHTML=d.entries.sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name)).map(e=>`<button data-name="${esc(e.name)}" data-dir="${e.directory}" ${e.symlink?'disabled':''}>${e.directory?'▱':'▧'} ${esc(e.name)}<small>${e.directory?'Folder':bytes(e.size)} · ${new Date(e.modified*1000).toLocaleDateString()} ${e.symlink?'· symbolic link':''}</small></button>`).join('')||'<p class="empty">This folder is empty.</p>';$('#file-list').querySelectorAll('button').forEach(b=>b.onclick=()=>Promise.resolve().then(async()=>{if(b.dataset.dir==='true'){path=join(b.dataset.name);await browse();}else await open(join(b.dataset.name));}).catch(e=>notice(e.message)));}
 async function open(name,newFile=false){if(dirty&&!confirm('Discard unsaved edits?'))return;file=name;const image=/\.(png|jpe?g|gif|webp)$/i.test(name);$('#file-editor').classList.remove('hidden');$('#editor-name').textContent=name;$('#image-preview').classList.toggle('hidden',!image);$('#editor').classList.toggle('hidden',image);editor?.destroy();$('#editor').innerHTML='';if(image){$('#image-preview').src='/api/files/image?path='+encodeURIComponent(name);return;}const d=newFile?{text:'',revision:null}:await api('files/read?path='+encodeURIComponent(name));revision=d.revision;const lang=languages.find(x=>x.extensions.includes(name.split('.').pop()));const extensions=[basicSetup,oneDark,EditorView.lineWrapping,EditorView.updateListener.of(u=>{if(u.docChanged){dirty=true;$('#dirty').textContent='Unsaved';$('#dirty').className='dirty';}})];if(lang)extensions.push(await lang.load());editor=new EditorView({doc:d.text,extensions,parent:$('#editor')});dirty=false;$('#dirty').textContent='';$('#file-editor').scrollIntoView({behavior:'smooth'});}
 bind('#files-go',async()=>{path=$('#file-path').value;await browse();});bind('#files-up',async()=>{path=path.split('/').slice(0,-1).join('/')||'.';await browse();});let debounce;$('#file-search').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(()=>browse().catch(e=>notice(e.message)),250);};
 bind('#file-new',async()=>{const n=prompt('New filename');if(n)await open(join(n),true);});bind('#folder-new',async()=>{const n=prompt('Folder name');if(n){await api('files/action',{action:'mkdir',path:join(n)});await browse();}});
 bind('#file-save',async()=>{if(!editor)return;const r=await api('files/save',{path:file,text:editor.state.doc.toString(),revision});revision=r.revision;dirty=false;$('#dirty').textContent='Saved';});
 bind('#file-download',()=>{const a=document.createElement('a');a.href='/api/files/download?path='+encodeURIComponent(file);a.click();});
 for(const [id,action] of [['#file-rename','move'],['#file-copy','copy']])bind(id,async()=>{const target=prompt('Destination path within your home folder',file);if(target){await api('files/action',{action,path:file,target});dirty=false;await browse();}});
 bind('#file-delete',async()=>{const confirmation=await dangerous('delete',file,'Delete '+file+'? This cannot be undone.');if(confirmation){await api('files/action',{action:'delete',path:file,confirmation});dirty=false;await browse();}});
 bind('#upload',()=>$('#upload-input').click());$('#upload-input').onchange=async()=>{try{const f=$('#upload-input').files[0];if(!f)return;if(f.size>2*1024*1024)throw new Error('Upload limit is 2 MiB.');const data=new Uint8Array(await f.arrayBuffer());let binary='';for(let i=0;i<data.length;i+=8192)binary+=String.fromCharCode(...data.subarray(i,i+8192));await api('files/save',{path:join(f.name),base64:btoa(binary)});await browse();}catch(e){notice(e.message);}};
 await browse();const before=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);cleanup=()=>{clearTimeout(debounce);editor?.destroy();window.removeEventListener('beforeunload',before);};
}
async function systemPage(){
 main.innerHTML='<h1>System</h1><div id="system-values" class="grid"></div><h2>Processes</h2><input id="process-search" class="wide" placeholder="Search processes" aria-label="Search processes"><div id="process-list" class="list"></div>';
 let closed=false,timer,rows=[];function show(){const q=$('#process-search').value.toLowerCase();$('#process-list').innerHTML=rows.filter(p=>p.name.toLowerCase().includes(q)).slice(0,100).map(p=>`<div class="card"><strong>${esc(p.name)}</strong><small> · PID ${p.pid} · ${bytes(p.ram)} · ${p.cpu.toFixed(1)}%</small><div class="row">${p.protected?'<small>Protected process</small>':`<button data-pid="${p.pid}" data-force="false">Terminate</button><button data-pid="${p.pid}" data-force="true" class="danger">Force kill</button>`}</div></div>`).join('');$('#process-list').querySelectorAll('button').forEach(b=>b.onclick=async()=>{try{const p=rows.find(p=>p.pid===Number(b.dataset.pid));const force=b.dataset.force==='true';const c=await dangerous(force?'kill':'terminate',p.pid,`${force?'Force kill':'Terminate'} ${p.name} (${p.pid})?`);if(c)await api('processes/signal',{pid:p.pid,created:p.create_time,force,confirmation:c});}catch(e){notice(e.message);}});}
 async function refresh(){try{const d=await api('system');rows=await api('processes');if(closed)return;$('#system-values').innerHTML=[['CPU',d.cpu.toFixed(1)+'%'],['RAM',bytes(d.ram.used)+' / '+bytes(d.ram.total)],['SWAP',bytes(d.swap.used)],['DISK FREE',bytes(d.disk.free)],['LOAD',d.load.map(n=>n.toFixed(2)).join(' / ')],['UPTIME',Math.floor(d.uptime/3600)+' hours'],['BATTERY',d.battery?d.battery.percent+'% '+(d.battery.power_plugged?'AC':'battery'):'Unavailable'],['TEMPERATURE',d.temperatures.map(t=>esc(t.label)+': '+t.celsius+'°C').join('<br>')||'Unavailable'],['NETWORK RECEIVED',bytes(d.network.bytes_recv)],['NETWORK SENT',bytes(d.network.bytes_sent)]].map(([k,v])=>`<div class="card"><small>${k}</small><p>${v}</p></div>`).join('');show();}catch(e){notice(e.message);}finally{if(!closed)timer=setTimeout(refresh,5000);}}
 $('#process-search').oninput=show;await refresh();cleanup=()=>{closed=true;clearTimeout(timer);};
}
async function evPage(){
 const d=await api('ev');let recording=null,timer=null,closed=false,starting=false,turn=0;const reply=new ReplyAudio();
 main.innerHTML=`<div class="topbar"><h1>Carlos</h1><button id="ev-restart">Restart</button></div><p id="ev-status" class="details">${esc(d.payload?.state||d.error||'Offline')} · ${esc(d.payload?.privacy||'NORMAL')}</p><div class="card"><small>COMPONENT READINESS</small>${Object.entries(d.payload?.readiness?.components||{}).map(([name,state])=>`<div class="row"><span>${esc(name)}</span><strong>${esc(state)}</strong></div>`).join('')}<p class="details">${esc(d.payload?.readiness?.state||'Not observed')}</p></div><div id="ev-output" class="message"></div><div id="ev-approval"></div><textarea id="ev-input" rows="3" placeholder="Message Carlos…"></textarea><div class="row"><button id="ev-send" class="primary">Send</button><button id="ev-record">🎙 Record</button><button id="ev-stop">Stop task</button></div><p class="details">Record up to 20 seconds, review the transcript, then Send. Speech is transcribed locally on your computer.</p><label><input type="checkbox" id="ev-phone-voice" checked> Speak replies on this phone</label><label>Privacy <select id="ev-privacy">${['NORMAL','LOCAL ONLY','PRIVATE SESSION','DO NOT LISTEN','GUEST'].map(m=>`<option ${d.payload?.privacy===m?'selected':''}>${m}</option>`).join('')}</select></label><div class="row"><button id="ev-events">Events</button><button id="ev-snapshot">Detailed status</button></div>`;
 function show(r){if(closed)return;const p=r.payload||r;$('#ev-output').textContent=p.response||p.error||pretty(p);$('#ev-approval').replaceChildren();const c=p.confirmation;if(c){const label=document.createElement('p');label.textContent=c.reason+' '+c.tool;$('#ev-approval').append(label);for(const [name,approved] of [['Approve',true],['Deny',false]]){const b=document.createElement('button');b.textContent=name;b.onclick=async()=>{try{show(await api('ev',{action:'confirm',id:c.id,approval_token:c.approval_token,approved}));}catch(e){notice(e.message);}};$('#ev-approval').append(b);}}}
 bind('#ev-send',async()=>{const text=$('#ev-input').value.trim();if(!text)return;const currentTurn=++turn;reply.stop();const phone_voice=$('#ev-phone-voice').checked;if(phone_voice)await reply.unlock();$('#ev-input').value='';$('#ev-output').textContent='Carlos is working…';const result=await api('ev',{action:'ask',text,phone_voice});if(closed||currentTurn!==turn)return;show(result);if(phone_voice&&result.payload?.response){$('#ev-status').textContent='Speaking…';try{await reply.speak(result.payload.response,text=>api('ev',{action:'synthesize',text}));}finally{if(!closed&&currentTurn===turn)$('#ev-status').textContent='Ready';}}});
 async function finish(){clearTimeout(timer);if(!recording)return;const audio=recording.stop();recording=null;if(closed)return;$('#ev-record').textContent='🎙 Record';$('#ev-status').textContent='Transcribing locally…';const r=await api('ev',{action:'transcribe',audio});if(closed)return;if(r.payload?.text){$('#ev-input').value=r.payload.text;$('#ev-status').textContent='Review your words, then tap Send.';}else show(r);}
 bind('#ev-record',async()=>{reply.stop();turn++;if(recording)return finish();if(starting)return;starting=true;try{const r=await startRecording(seconds=>{if(!closed)$('#ev-status').textContent='Recording '+seconds.toFixed(1)+' / 20 s';});if(closed){r.cancel();return;}recording=r;$('#ev-record').textContent='Stop recording';timer=setTimeout(()=>finish().catch(e=>notice(e.message)),20000);}finally{starting=false;}});
 bind('#ev-stop',async()=>{reply.stop();turn++;recording?.cancel();recording=null;clearTimeout(timer);$('#ev-record').textContent='🎙 Record';show(await api('ev',{action:'stop'}));});
 $('#ev-privacy').onchange=async()=>{reply.stop();turn++;recording?.cancel();recording=null;clearTimeout(timer);try{await api('ev',{action:'privacy',mode:$('#ev-privacy').value});navigate('ev');}catch(e){notice(e.message);}};
 bind('#ev-events',async()=>{$('#ev-output').textContent=pretty(await api('ev',{action:'events'}));});
 bind('#ev-snapshot',async()=>{$('#ev-output').textContent=pretty(await api('ev',{action:'snapshot'}));});
 bind('#ev-restart',async()=>{const c=await dangerous('ev.restart',null,'Restart Carlos? Any active task may be interrupted.');if(c){await api('ev',{action:'restart',confirmation:c});navigate('ev');}});
 cleanup=()=>{closed=true;turn++;clearTimeout(timer);recording?.cancel();reply.close().catch(()=>{});};
}
async function chatPage(){main.innerHTML='<h1>Carlos Mobile</h1><p class="muted">Your computer, in plain language.</p><div id="chat-output"></div><textarea id="chat-input" rows="3" placeholder="What is my PC doing?"></textarea><button id="chat-send" class="primary wide">Send</button>';bind('#chat-send',async()=>{const text=$('#chat-input').value;const d=await api('chat',{text});const box=document.createElement('div');box.className='message';box.textContent=d.message||d.ev?.payload?.response||(d.system?`CPU ${d.system.cpu.toFixed(0)}% · Memory ${bytes(d.system.ram.used)} of ${bytes(d.system.ram.total)}`:pretty(d));$('#chat-output').append(box);if(d.navigate)await navigate(d.navigate);if(d.suggestedAction){const b=document.createElement('button');b.textContent=d.suggestedAction;b.onclick=()=>api('action',{action:d.suggestedAction}).catch(e=>notice(e.message));box.append(b);}});}
async function settings(){const d=await api('devices');main.innerHTML='<h1>Paired devices</h1><p class="muted">Revoking a device immediately disconnects it.</p><div class="list">'+d.map(x=>`<div class="card"><strong>${esc(x.name)}</strong><p class="details">Last login: ${new Date(x.last_seen*1000).toLocaleString()}</p><button class="danger" data-revoke="${x.id}">Revoke</button></div>`).join('')+'</div><div class="row"><button id="reauth">Verify passkey</button><button id="logout">Sign out</button></div><h2>Notifications</h2><p class="muted">Enable notifications to hear when Codex finishes or needs your input. On iPhone, add HoloHand to your Home Screen first.</p><button id="push-enable">Enable notifications</button><button id="events-show">Recent events</button><pre id="events" class="output hidden"></pre>';main.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{try{const c=await dangerous('revoke',b.dataset.revoke,'Revoke this device? It must pair locally again.');if(c){await api('devices/revoke',{device:b.dataset.revoke,confirmation:c});navigate('settings');}}catch(e){notice(e.message);}});bind('#push-enable',async()=>{if(!('PushManager' in window))throw new Error('Add Carlos Mobile to your Home Screen and open it there first.');if(await Notification.requestPermission()!=='granted')throw new Error('Notifications were not allowed.');const reg=await navigator.serviceWorker.ready;const {key}=await api('push/key');const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await api('push/subscribe',sub.toJSON());notice('Notifications enabled.');});bind('#reauth',unlock);bind('#logout',async()=>{await api('logout',{});authenticated=false;login();});bind('#events-show',async()=>{$('#events').textContent=pretty(await api('events'));$('#events').classList.remove('hidden');});}
async function diagnostics(){const start=performance.now();const d=await api('diagnostics');const elapsed=performance.now()-start;main.innerHTML=`<h1>Connection</h1><div class="card"><div class="eyebrow">IPHONE → TAILSCALE → ${esc(location.hostname.split('.')[0].toUpperCase())}</div><h2>${elapsed.toFixed(0)} ms</h2><p class="muted">Measured API round trip</p></div><pre class="output">${esc(pretty(d))}</pre><p class="details">Stream quality settings are targets. Actual FPS and cellular performance require measurement on the connected phone.</p>`;}
$('#home').onclick=()=>navigate('home');$('#connection').onclick=()=>authenticated?navigate('diagnostics'):unlock().catch(e=>notice(e.message));document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
window.addEventListener('online',()=>{status('RECONNECTING');check();});window.addEventListener('offline',()=>status('OFFLINE'));
async function check(){clearTimeout(networkTimer);try{const s=await api('me');csrf=s.csrf;authenticated=true;status('● CONNECTED',true);}catch(e){status(navigator.onLine?'UNLOCK REQUIRED':'OFFLINE');}networkTimer=setTimeout(check,30000);}
(async()=>{await check();if(authenticated)await navigate(localStorage.getItem('hh-page')||'home');else login();})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').then(r=>{r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)notice('Carlos update ready. Close and reopen the app when convenient.');});});}).catch(()=>{});
