import {homedir, hostname} from 'node:os';
import {test,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const state=`${homedir()}/.cache/holohand-browser-tests`;
test('passkey pairing, real terminal, file edit, and immediate revocation',async({page,context})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');
 await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 writeFileSync(state+'/pairing.json',JSON.stringify({hash:createHash('sha256').update('739184').digest('hex'),expires:Date.now()/1000+300}),{mode:0o600});
 await page.goto('/');await page.getByText('Pair this iPhone',{exact:true}).click();await page.getByLabel('Pairing code').fill('739184');await page.getByLabel('Device name').fill('Automated browser test');await page.getByRole('button',{name:'Pair with computer'}).click();
 await expect(page.getByRole('heading',{name:hostname().toUpperCase()})).toBeVisible({timeout:20000});
 await page.screenshot({path:'test-results/mobile-home.png',fullPage:true});
 await page.getByRole('button',{name:'Terminal',exact:true}).click();await expect(page.locator('#term-status')).toContainText('Connected',{timeout:15000});
 await page.locator('.xterm-helper-textarea').fill("printf 'HOLOHAND_PTY_OK\\n'\n");await page.keyboard.press('Enter');
 await expect(page.locator('.xterm-screen')).toContainText('HOLOHAND_PTY_OK',{timeout:10000});
 await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('button',{name:'Files & editor'}).click();
 const result=await page.evaluate(async()=>{const me=await(await fetch('/api/me')).json();const h={'Content-Type':'application/json','X-HoloHand-CSRF':me.csrf};const path='.cache/holohand-browser-tests/host-file.txt';const r=await fetch('/api/files/save',{method:'POST',headers:h,body:JSON.stringify({path,text:'HOLOHAND_FILE_OK\n'})});return {status:r.status,body:await r.json()};});expect(result.status).toBe(200);
 await page.getByLabel('Folder path').fill('.cache/holohand-browser-tests');await page.getByRole('button',{name:'Go',exact:true}).click();await page.getByRole('button',{name:/host-file.txt/}).click();await expect(page.locator('.cm-content')).toContainText('HOLOHAND_FILE_OK');
 await page.screenshot({path:'test-results/mobile-editor.png',fullPage:true});
 const checks=await page.evaluate(async()=>{const me=await(await fetch('/api/me')).json();const h={'Content-Type':'application/json','X-HoloHand-CSRF':me.csrf};const bad=await fetch('/api/files/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'bad',text:'bad'})});const traversal=await fetch('/api/files/read?path=/etc/passwd');const confirm=await(await fetch('/api/confirm',{method:'POST',headers:h,body:JSON.stringify({action:'revoke',target:me.device})})).json();const revoke=await fetch('/api/devices/revoke',{method:'POST',headers:h,body:JSON.stringify({device:me.device,confirmation:confirm.confirmation})});const after=await fetch('/api/system');return [bad.status,traversal.status,revoke.status,after.status];});
 expect(checks).toEqual([403,400,200,401]);expect(errors).toEqual([]);
});
